[package]
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
edition = "2021"
license = "Apache-2.0/MIT"
name = "chainfile"
rust-version = "1.68.0"
publish = true
description = "A crate for working with genomics chain files."
version = "0.2.0"

[dev-dependencies]
flate2 = "1.0.25"
noodles = { version = "0.35.0", features = ["core", "fasta"] }

[dependencies]
rust-lapper = "1.1.0"
